# Generated by Django 4.2.1 on 2023-05-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('college_name', models.CharField(choices=[('CAH', 'CAH'), ('CBA', 'CBA'), ('CCJE', 'CCJE'), ('CEAT', 'CEAT'), ('CHTM', 'CHTM'), ('CNHS', 'CNHS'), ('CS', 'CS'), ('CTE', 'CTE'), ('LHS', 'LHS')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.BigIntegerField(db_column='sid', primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('corporate_email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('date_add', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myelibrary_app.college')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
