# Generated by Django 4.2.1 on 2023-05-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myelibrary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(db_column='admin_id', primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.IntegerField(db_column='bid', primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=500)),
                ('book_author', models.CharField(max_length=50)),
                ('book_isbn', models.BigIntegerField()),
                ('year_published', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('borrow_id', models.IntegerField(db_column='borrow_id', primary_key=True, serialize=False)),
                ('time_borrow', models.DateTimeField()),
                ('time_return', models.DateTimeField(blank=True, null=True)),
                ('fines', models.IntegerField()),
                ('action', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_isbn', models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, to='myelibrary_app.book')),
                ('coll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myelibrary_app.college')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myelibrary_app.student')),
            ],
            options={
                'db_table': 'borrow',
            },
        ),
    ]
