# Generated by Django 4.2.1 on 2023-05-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myelibrary_app', '0002_admin_book_alter_college_id_alter_student_date_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.AutoField(db_column='admin_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='bid',
            field=models.AutoField(db_column='bid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_id',
            field=models.AutoField(db_column='borrow_id', primary_key=True, serialize=False),
        ),
    ]
