# Generated by Django 4.2.1 on 2023-05-28 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myelibrary_app', '0003_alter_admin_admin_id_alter_book_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myelibrary_app.book'),
        ),
    ]
