# Generated by Django 4.2.1 on 2023-05-28 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myelibrary_app', '0004_alter_borrow_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_isbn',
            field=models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, to='myelibrary_app.book'),
        ),
    ]
