# Generated by Django 4.2.1 on 2023-05-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myelibrary_app', '0005_alter_borrow_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='action',
            new_name='status',
        ),
    ]
